In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from dotenv import load_dotenv
import janitor
import os
from pathlib import Path
import openpyxl
import sqlalchemy as sa


# Desactivar notación científica
pd.set_option('display.float_format', lambda x: '%.3f' % x)
np.set_printoptions(suppress=True)


# Cargar variables de entorno
load_dotenv()


print("✅ Librerías importadas correctamente")

✅ Librerías importadas correctamente

In [2]:
con = sa.create_engine('sqlite:///../02_datos/01_Originales/hipermercado.db')

from sqlalchemy import inspect
insp = inspect(con)
tablas = insp.get_table_names()
tablas

['calendar', 'sales', 'sell_prices']

In [3]:
cal = pd.read_sql('calendar', con)
cal.drop(columns='index', inplace=True)
cal.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2
0,2013-01-01,11249,Tuesday,4,1,2013,d_704,NewYear,National,None,None
1,2013-01-02,11249,Wednesday,5,1,2013,d_705,None,None,None,None
2,2013-01-03,11249,Thursday,6,1,2013,d_706,None,None,None,None
3,2013-01-04,11249,Friday,7,1,2013,d_707,None,None,None,None
4,2013-01-05,11250,Saturday,1,1,2013,d_708,None,None,None,None

In [4]:
cal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1095 non-null   object
 1   wm_yr_wk      1095 non-null   int64
 2   weekday       1095 non-null   object
 3   wday          1095 non-null   int64
 4   month         1095 non-null   int64
 5   year          1095 non-null   int64
 6   d             1095 non-null   object
 7   event_name_1  87 non-null     object
 8   event_type_1  87 non-null     object
 9   event_name_2  3 non-null      object
 10  event_type_2  3 non-null      object
dtypes: int64(4), object(7)
memory usage: 94.2+ KB

In [5]:
sales = pd.read_sql('sales', con)
sales.drop(columns='index', inplace=True)
sales.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d_704,d_705,d_706,d_707,...,d_1789,d_1790,d_1791,d_1792,d_1793,d_1794,d_1795,d_1796,d_1797,d_1798
0,FOODS_3_090_CA_3_validation,FOODS_3_090,FOODS_3,FOODS,CA_3,CA,0,224,241,232,...,5,2,0,0,6,0,6,0,0,0
1,FOODS_3_120_CA_3_validation,FOODS_3_120,FOODS_3,FOODS,CA_3,CA,0,0,0,0,...,54,63,44,0,65,90,104,73,76,97
2,FOODS_3_202_CA_3_validation,FOODS_3_202,FOODS_3,FOODS,CA_3,CA,20,23,23,25,...,43,40,39,0,29,33,27,13,26,47
3,FOODS_3_252_CA_3_validation,FOODS_3_252,FOODS_3,FOODS,CA_3,CA,34,27,40,49,...,31,43,32,0,52,37,32,29,34,27
4,FOODS_3_288_CA_3_validation,FOODS_3_288,FOODS_3,FOODS,CA_3,CA,0,0,0,0,...,29,45,28,0,46,36,40,31,46,36

In [6]:
# Pasar a transaccional
sales = sales.melt(id_vars = sales.columns[0:6],
                     var_name = 'd',
                     value_name = 'ventas')

sales.drop(columns='id', inplace=True)
sales

           item_id  dept_id cat_id store_id state_id       d  ventas
0      FOODS_3_090  FOODS_3  FOODS     CA_3       CA   d_704       0
1      FOODS_3_120  FOODS_3  FOODS     CA_3       CA   d_704       0
2      FOODS_3_202  FOODS_3  FOODS     CA_3       CA   d_704      20
3      FOODS_3_252  FOODS_3  FOODS     CA_3       CA   d_704      34
4      FOODS_3_288  FOODS_3  FOODS     CA_3       CA   d_704       0
...            ...      ...    ...      ...      ...     ...     ...
21895  FOODS_3_329  FOODS_3  FOODS     CA_4       CA  d_1798       6
21896  FOODS_3_555  FOODS_3  FOODS     CA_4       CA  d_1798       5
21897  FOODS_3_586  FOODS_3  FOODS     CA_4       CA  d_1798      11
21898  FOODS_3_587  FOODS_3  FOODS     CA_4       CA  d_1798      16
21899  FOODS_3_714  FOODS_3  FOODS     CA_4       CA  d_1798      21

[21900 rows x 7 columns]

In [7]:
prices = pd.read_sql('sell_prices', con)
prices.drop(columns='index', inplace=True)
prices.head()

  store_id      item_id  wm_yr_wk  sell_price
0     CA_3  FOODS_3_090     11249       1.250
1     CA_3  FOODS_3_090     11250       1.250
2     CA_3  FOODS_3_090     11251       1.250
3     CA_3  FOODS_3_090     11252       1.250
4     CA_3  FOODS_3_090     11301       1.380

In [8]:
# Primero unir la tabla cal con sales, ya que necesitamos la columna 'd' para unir con prices
df = sales.merge(cal, on='d', how='left')
df

,item_id,dept_id,cat_id,store_id,state_id,d,ventas,date,wm_yr_wk,weekday,wday,month,year,event_name_1,event_type_1,event_name_2,event_type_2
0,FOODS_3_090,FOODS_3,FOODS,CA_3,CA,d_704,0,2013-01-01,11249,Tuesday,4,1,2013,NewYear,National,None,None
1,FOODS_3_120,FOODS_3,FOODS,CA_3,CA,d_704,0,2013-01-01,11249,Tuesday,4,1,2013,NewYear,National,None,None
2,FOODS_3_202,FOODS_3,FOODS,CA_3,CA,d_704,20,2013-01-01,11249,Tuesday,4,1,2013,NewYear,National,None,None
3,FOODS_3_252,FOODS_3,FOODS,CA_3,CA,d_704,34,2013-01-01,11249,Tuesday,4,1,2013,NewYear,National,None,None
4,FOODS_3_288,FOODS_3,FOODS,CA_3,CA,d_704,0,2013-01-01,11249,Tuesday,4,1,2013,NewYear,National,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21895,FOODS_3_329,FOODS_3,FOODS,CA_4,CA,d_1798,6,2015-12-31,11548,Thursday,6,12,2015,None,None,None,None
21896,FOODS_3_555,FOODS_3,FOODS,CA_4,CA,d_1798,5,2015-12-31,11548,Thursday,6,12,2015,None,None,None,None
21897,FOODS_3_586,FOODS_3,FOODS,CA_4,CA,d_1798,11,2015-12-31,11548,Thursday,6,12,2015,None,None,None,None
21898,FOODS_3_587,FOODS_3,FOODS,CA_4,CA,d_1798,16,2015-12-31,11548,Thursday,6,12,2015,None,None,None,None
21899,FOODS_3_714,FOODS_3,FOODS,CA_4,CA,d_1798,21,2015-12-31,11548,Thursday,6,12,2015,None,None,None,None

In [9]:
# Unir df con la tabla prices
df = df.merge(prices, on=['store_id', 'item_id', 'wm_yr_wk'], how='left')
df

,item_id,dept_id,cat_id,store_id,state_id,d,ventas,date,wm_yr_wk,weekday,wday,month,year,event_name_1,event_type_1,event_name_2,event_type_2,sell_price
0,FOODS_3_090,FOODS_3,FOODS,CA_3,CA,d_704,0,2013-01-01,11249,Tuesday,4,1,2013,NewYear,National,None,None,1.250
1,FOODS_3_120,FOODS_3,FOODS,CA_3,CA,d_704,0,2013-01-01,11249,Tuesday,4,1,2013,NewYear,National,None,None,4.980
2,FOODS_3_202,FOODS_3,FOODS,CA_3,CA,d_704,20,2013-01-01,11249,Tuesday,4,1,2013,NewYear,National,None,None,4.280
3,FOODS_3_252,FOODS_3,FOODS,CA_3,CA,d_704,34,2013-01-01,11249,Tuesday,4,1,2013,NewYear,National,None,None,1.480
4,FOODS_3_288,FOODS_3,FOODS,CA_3,CA,d_704,0,2013-01-01,11249,Tuesday,4,1,2013,NewYear,National,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21895,FOODS_3_329,FOODS_3,FOODS,CA_4,CA,d_1798,6,2015-12-31,11548,Thursday,6,12,2015,None,None,None,None,2.980
21896,FOODS_3_555,FOODS_3,FOODS,CA_4,CA,d_1798,5,2015-12-31,11548,Thursday,6,12,2015,None,None,None,None,1.680
21897,FOODS_3_586,FOODS_3,FOODS,CA_4,CA,d_1798,11,2015-12-31,11548,Thursday,6,12,2015,None,None,None,None,1.680
21898,FOODS_3_587,FOODS_3,FOODS,CA_4,CA,d_1798,16,2015-12-31,11548,Thursday,6,12,2015,None,None,None,None,2.480
21899,FOODS_3_714,FOODS_3,FOODS,CA_4,CA,d_1798,21,2015-12-31,11548,Thursday,6,12,2015,None,None,None,None,1.580

In [10]:
# Reordenar columnas y poner fecha como indice
orden = ['date',
         'state_id',
         'store_id',
         'dept_id',
         'cat_id',
         'item_id',
         'wm_yr_wk',
         'd',
         'ventas',
         'sell_price',
         'year',
         'month',
         'wday',
         'weekday',
         'event_name_1',
         'event_type_1',
         'event_name_2',
         'event_type_2']
df = df[orden].set_index('date').sort_index()
df

,state_id,store_id,dept_id,cat_id,item_id,wm_yr_wk,d,ventas,sell_price,year,month,wday,weekday,event_name_1,event_type_1,event_name_2,event_type_2
date,,,,,,,,,,,,,,,,,
2013-01-01,CA,CA_3,FOODS_3,FOODS,FOODS_3_090,11249,d_704,0,1.250,2013,1,4,Tuesday,NewYear,National,None,None
2013-01-01,CA,CA_3,FOODS_3,FOODS,FOODS_3_120,11249,d_704,0,4.980,2013,1,4,Tuesday,NewYear,National,None,None
2013-01-01,CA,CA_3,FOODS_3,FOODS,FOODS_3_202,11249,d_704,20,4.280,2013,1,4,Tuesday,NewYear,National,None,None
2013-01-01,CA,CA_3,FOODS_3,FOODS,FOODS_3_252,11249,d_704,34,1.480,2013,1,4,Tuesday,NewYear,National,None,None
2013-01-01,CA,CA_3,FOODS_3,FOODS,FOODS_3_288,11249,d_704,0,NaN,2013,1,4,Tuesday,NewYear,National,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-12-31,CA,CA_4,FOODS_3,FOODS,FOODS_3_329,11548,d_1798,6,2.980,2015,12,6,Thursday,None,None,None,None
2015-12-31,CA,CA_4,FOODS_3,FOODS,FOODS_3_555,11548,d_1798,5,1.680,2015,12,6,Thursday,None,None,None,None
2015-12-31,CA,CA_4,FOODS_3,FOODS,FOODS_3_586,11548,d_1798,11,1.680,2015,12,6,Thursday,None,None,None,None
2015-12-31,CA,CA_4,FOODS_3,FOODS,FOODS_3_587,11548,d_1798,16,2.480,2015,12,6,Thursday,None,None,None,None
2015-12-31,CA,CA_4,FOODS_3,FOODS,FOODS_3_714,11548,d_1798,21,1.580,2015,12,6,Thursday,None,None,None,None

## Extraer y reservar el dataset de validación
#### Dado que es un problema de forecsting no podemos extraer el dataset de validacion de forma aleatoria. Este no estara compuesto por los ultimos datos disponibles, sino por los datos de un periodo futuro.

In [11]:
val = df['2015-12-01':'2015-12-31']
val.to_pickle('../02_datos/02_Validacion/validacion.pkl')

In [12]:
train = df[:'2015-11-30']
train.to_pickle('../02_datos/03_Entrenamiento/train.pkl')